# -*- coding: utf-8 -*-
"""05_channel_flow_with_gmsh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JaWNdbZqJ0ZzJ_Swvtcewey92iohOIl

# The Laplace Problem
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f

import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = "false"
from tqdm import tqdm

import jax
import jax.numpy as jnp
from jax.tree_util import Partial
# jax.config.update('jax_platform_name', 'cpu')           ## CPU is faster here !

from updec import *

"""## Using Updec"""

facet_types_vel = {"Wall":"d", "Square":"d", "Inflow":"d", "Outflow":"n"}
facet_types_phi = {"Wall":"n", "Square":"n", "Inflow":"n", "Outflow":"n"}

cloud_vel = GmshCloud(filename="./demos/meshes/cylinder.msh", facet_types=facet_types_vel, support_size="max")       ## TODO do not hardcode this path
cloud_phi = GmshCloud(filename="./demos/meshes/cylinder.msh", facet_types=facet_types_phi, support_size="max")       ## TODO do not hardcode this path

cloud_vel.visualize_cloud(figsize=(20,1.4), s=12, title="Cloud for velocity");
cloud_phi.visualize_cloud(figsize=(20,1.4), s=12, title=r"Cloud for $\phi$");

print("Total number of nodes:", cloud_vel.N)
# plt.show()
# exit(0)


RBF = polyharmonic      ## Can define which rbf to use
MAX_DEGREE = 4

parabolic = jax.jit(lambda x: 1.5 - 6*(x[1]**2))
zero = jax.jit(lambda x: 0.0)
one = jax.jit(lambda x: -0.25)

bc_u = {"Wall":zero, "Square":zero, "Inflow":parabolic, "Outflow":zero}
bc_v = {"Wall":zero, "Square":zero, "Inflow":zero, "Outflow":zero}
bc_phi = {"Wall":zero, "Square":zero, "Inflow":zero, "Outflow":zero}


Du = Re = 200
DeltaT = 0.00001

@Partial(jax.jit, static_argnums=[2,3])
def diff_operator_u(x, center=None, rbf=None, monomial=None, fields=None):
    u = nodal_value(x, center, rbf, monomial)
    # u = nodal_laplacian(x, center, rbf, monomial)
    return u

@Partial(jax.jit, static_argnums=[2])
def rhs_operator_u(x, centers=None, rbf=None, fields=None):
    u = value(x, fields[:, 0], centers, rbf) 
    v = value(x, fields[:, 1], centers, rbf) 
    U = jnp.array([u,v])

    grad_u = gradient(x, fields[:, 0], centers, rbf)
    grad_px = gradient(x, fields[:, 2], centers, rbf)[0]
    lap_u = laplacian(x, fields[:, 0], centers, rbf)

    return  u + DeltaT*(jnp.dot(U, grad_u) - grad_px + lap_u/Re)



@Partial(jax.jit, static_argnums=[2,3])
def diff_operator_v(x, center=None, rbf=None, monomial=None, fields=None):
    v = nodal_value(x, center, rbf, monomial)
    return  v

@Partial(jax.jit, static_argnums=[2])
def rhs_operator_v(x, centers=None, rbf=None, fields=None):
    u = value(x, fields[:, 0], centers, rbf) 
    v = value(x, fields[:, 1], centers, rbf) 
    U = jnp.array([u,v])

    grad_v = gradient(x, fields[:, 1], centers, rbf)
    grad_py = gradient(x, fields[:, 2], centers, rbf)[1]
    lap_v = laplacian(x, fields[:, 1], centers, rbf)

    return v + DeltaT*(jnp.dot(U, grad_v) - grad_py + lap_v/Re)



@Partial(jax.jit, static_argnums=[2,3])
def diff_operator_phi(x, center=None, rbf=None, monomial=None, fields=None):
    return nodal_laplacian(x, center, rbf, monomial)

@Partial(jax.jit, static_argnums=[2])
def rhs_operator_phi(x, centers=None, rbf=None, fields=None):
    return divergence(x, fields[:, :2], centers, rbf)


## Initial states, all defined on cloud_vel
u = jnp.zeros((cloud_vel.N,))
v = jnp.zeros((cloud_vel.N,))
p_ = jnp.zeros((cloud_phi.N,))       ## on cloud_phi

nb_iter = 1

for i in tqdm(range(nb_iter)):
    # print("Starting iteration %d" % i)

    ## TODO Interpolate p and gradphi onto cloud_vel
    p = interpolate_field(p_, cloud_phi, cloud_vel)

    usol = pde_solver(diff_operator=diff_operator_u, 
                    # diff_args=[v], 
                    rhs_operator = rhs_operator_u, 
                    rhs_args=[u,v,p], 
                    cloud = cloud_vel, 
                    boundary_conditions = bc_u,
                    rbf=RBF,
                    max_degree=MAX_DEGREE)

    vsol = pde_solver(diff_operator=diff_operator_v,
                    # diff_args=[v],
                    rhs_operator = rhs_operator_v,
                    rhs_args=[u,v,p], 
                    cloud = cloud_vel, 
                    boundary_conditions = bc_v,
                    rbf=RBF,
                    max_degree=MAX_DEGREE)

    ustar , vstar = usol.vals, vsol.vals     ## Star
    Ustar = jnp.stack([ustar,vstar], axis=-1)

    ## TODO Interpolaate Ustar onto cloud_phi
    u_ = interpolate_field(ustar, cloud_vel, cloud_phi)
    v_ = interpolate_field(vstar, cloud_vel, cloud_phi)

    phisol_ = pde_solver(diff_operator=diff_operator_phi,
                    # diff_args=[v],
                    rhs_operator = rhs_operator_phi,
                    rhs_args=[u_,v_], 
                    cloud = cloud_phi, 
                    boundary_conditions = bc_phi,
                    rbf=RBF,
                    max_degree=MAX_DEGREE)

    p_ = p_ + phisol_.vals
    gradphi_ = gradient_vec(cloud_phi.sorted_nodes, phisol_.coeffs, cloud_phi.sorted_nodes, RBF)        ## TODO use Pde_solver here instead ?

    ## TODO Visualise gradphi and make sure it's correct
    # Try a normal poisson probblem with neumann bd conditions


    ## TODO Interpolate p and gradphi onto cloud_vel
    gradphi = interpolate_field(gradphi_, cloud_phi, cloud_vel)

    # U = Ustar - gradphi
    U = Ustar
    u, v = U[:,0], U[:,1]

    vel = jnp.linalg.norm(U, axis=-1)
cloud_vel.visualize_field(vel, cmap="jet", title="Velocity norm", projection="2d", ax=None, figsize=(20,1.5));



# u = usol.vals
# v = vsol.vals
cloud_vel.visualize_field(u, cmap="jet", title="Velocity along x", projection="2d", ax=None, figsize=(20,1.5));
cloud_vel.visualize_field(v, cmap="jet", title="Velocity along y", projection="2d", ax=None, figsize=(20,1.5));
cloud_phi.visualize_field(p_, cmap="jet", title="Pressure", projection="2d", ax=None, figsize=(20,1.5));

plt.show()
