# operators.pde_solver_jit { #updes.operators.pde_solver_jit }

`operators.pde_solver_jit(diff_operator, rhs_operator, cloud, boundary_conditions, rbf, max_degree, diff_args=None, rhs_args=None)`

PDE solver just-in-time compiled with respect to the boundary conditions

Args:
    diff_operator (callable): The differential operator (the left-hand side of the PDE), evaluated at each internal point with respect to each RBF centroid seperately, i.e. *nodal* evaluation.
    rhs_operator (callable): The right-hand-side operator, evaluated at each node with respect to all centroids at once, i.e. *global* evaluation.
    cloud (Cloud): The cloud on which to solve the PDE
    boundary_conditions (dict): The boundary conditions to enforce, one for each facet given by either a function or an approiate vector
    rbf (callable): The radial basis function to use
    max_degree (int): The maximum degree of the polynomial to use in the RBF
    diff_args (list, optional): The arguments to pass to the differential operator. Defaults to None.
    rhs_args (list, optional): The arguments to pass to the right-hand-side operator. Defaults to None.

Returns:
    SteadySol: A named tuple containing the values and coefficients of the solution, as well as the matrix used in the linear solve