name: Updes CI/CD

on: [push]

jobs:
  linux-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Updes & Pytest
      run: |
        pip install --upgrade pip && pip install --upgrade "jax[cpu]" && python -m pip install -e .
    - name: Run package-wide test
      run: |
        pytest --pyargs updes

